<input type={'checkbox'} checked></input>;
;
;
;
<input type={'checkbox'} checked={true}></input>;
;
;
;
<input type={'checkbox'} checked={false}></input>;
;
;
;
<input type={'checkbox'} checked={true.toString()}></input>;
